title: 翻墙软件VPN推荐指南
SEOTitle: 翻墙软件VPN推荐指南
header-img: img/post-bg-desk.jpg
email: qiubaiying@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone"
url: "https://vpncn.github.io/"          # your host, for absolute URL
github_repo: "https://github.com/vpncn/vpncn.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: 

google_analytics: UA-
theme: jekyll-theme-cayman
